# Generated by Django 5.1.3 on 2025-01-08 09:07

import course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('programming', 'Programming Exercise'), ('traditional', 'Traditional Exercise'), ('jupyter', 'Jupyter Notebook Exercise')], default='traditional', help_text='Type of exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(help_text='Exercise file uploaded by user or group', upload_to=course.models.get_exercise_file_path, validators=[course.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='ExerciseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Additional material file for the exercise', upload_to=course.models.get_material_file_path, validators=[course.models.validate_file_size])),
                ('description', models.CharField(help_text='Brief description of the material', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='JupyterLabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(help_text='JupyterLab image file', upload_to=course.models.get_jupyterlab_image_path, validators=[course.models.validate_file_size])),
                ('version', models.CharField(help_text='Version of the JupyterLab image', max_length=50)),
                ('requirements', models.TextField(blank=True, help_text='Additional requirements or dependencies for the image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.OneToOneField(limit_choices_to={'exercise_type': 'jupyter'}, on_delete=django.db.models.deletion.CASCADE, related_name='jupyterlab_image', to='course.exercise')),
            ],
        ),
    ]
