# Generated by Django 5.1.3 on 2025-01-13 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_exercise_exercise_type_alter_exercise_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='jupyterlabimage',
            name='exercise',
        ),
        migrations.AddField(
            model_name='jupyterlabimage',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jupyterlab_image', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('traditional', 'Traditional Exercise'), ('jupyter', 'Jupyter Notebook Exercise')], default='traditional', help_text='Type of exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='course_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='course_grou_created_42f195_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('instructor',), name='one_course_per_instructor'),
        ),
    ]
