# Generated by Django 5.1.3 on 2025-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_group_options_remove_jupyterlabimage_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jupyterlabimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='jupyterlabimage',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jupyterlabimage',
            name='version',
        ),
        migrations.AddField(
            model_name='jupyterlabimage',
            name='image_name',
            field=models.CharField(default=1, help_text="Docker Hub image name (e.g., 'jupyter/datascience-notebook:latest')", max_length=255),
            preserve_default=False,
        ),
    ]
