# Generated by Django 5.1.3 on 2025-01-13 09:58

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_jupyterlabimage_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, help_text='Exercise file uploaded by user or group', null=True, upload_to=course.models.get_exercise_file_path, validators=[course.models.validate_file_size]),
        ),
    ]
