# Generated by Django 5.1.3 on 2025-01-15 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_submissionfile_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(default=1, help_text='Instructor responsible for this module', limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['instructor'], name='course_modu_instruc_56d7f9_idx'),
        ),
    ]
