# Generated by Django 5.1.3 on 2025-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_module_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
