# Generated by Django 5.1.3 on 2025-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_submission_passed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['passed'], name='course_subm_passed_1a3cde_idx'),
        ),
    ]
