# Generated by Django 5.1.3 on 2025-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_submission_course_subm_passed_1a3cde_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='domain_name',
            field=models.CharField(blank=True, help_text='Domain name of the virtual machine where JupyterHub is hosted', max_length=255, null=True),
        ),
    ]
