# Generated by Django 5.1.3 on 2025-02-13 09:23

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to help describe the issue', null=True, upload_to=course.models.get_ticket_image_path, validators=[course.models.validate_file_size]),
        ),
    ]
