# Generated by Django 5.1.3 on 2025-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_key',
            field=models.CharField(blank=True, help_text='Enrollment key required for students to join the course', max_length=100, null=True),
        ),
    ]
