# Generated by Django 5.1.3 on 2025-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_course_enrollment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Professional')], default=1, help_text='Module difficulty level'),
        ),
    ]
