# Generated by Django 5.1.3 on 2025-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_module_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='maximum_points',
            field=models.PositiveIntegerField(default=10, help_text='Maximum points students can earn from the exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pass_points',
            field=models.PositiveIntegerField(default=5, help_text='Minimum points required for students to pass the exercise'),
        ),
    ]
