# Generated by Django 5.1.3 on 2025-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_exercise_maximum_points_exercise_pass_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'group_number'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AddField(
            model_name='group',
            name='group_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential group number starting from 1, automatically assigned', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pass_points',
            field=models.PositiveIntegerField(default=0, help_text='Minimum points required for students to pass the exercise'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'group_number'], name='course_grou_course__d4b716_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('course', 'group_number'), name='unique_group_number_per_course'),
        ),
    ]
