# Generated by Django 5.1.3 on 2025-05-26 12:06

from django.db import migrations


def assign_group_numbers(apps, schema_editor):
    """Assign sequential group numbers to existing groups."""
    Group = apps.get_model('course', 'Group')
    Course = apps.get_model('course', 'Course')
    
    # Process each course separately
    for course in Course.objects.all():
        groups = Group.objects.filter(course=course, group_number__isnull=True).order_by('id')
        for index, group in enumerate(groups, start=1):
            group.group_number = index
            group.save()


def reverse_assign_group_numbers(apps, schema_editor):
    """Reverse the group number assignment."""
    Group = apps.get_model('course', 'Group')
    Group.objects.all().update(group_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_add_group_number_field'),
    ]

    operations = [
        migrations.RunPython(assign_group_numbers, reverse_assign_group_numbers),
    ]
