# Generated by Django 5.1.3 on 2025-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_assign_group_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course start date', null=True),
        ),
    ]
