# Generated by Django 5.1.3 on 2025-06-12 09:20

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(help_text='A file submitted by the student', max_length=255, upload_to=course.models.get_submission_file_path, validators=[course.models.validate_file_size]),
        ),
    ]
