# Generated by Django 5.1.3 on 2025-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Professional'), (5, 'Demo')], default=1, help_text='Course difficulty level'),
        ),
        migrations.AlterField(
            model_name='module',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Professional'), (5, 'Demo')], default=1, help_text='Module difficulty level'),
        ),
    ]
