from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('dev-login/', views.dev_login, name='dev_login'),
    path('manage/<int:course_id>/groups/', views.manage_groups, name='manage_groups'),
    path('manage/<int:course_id>/groups/create/', views.manage_create_group, name='manage_create_group'),
    path('manage/<int:course_id>/groups/<int:group_id>/delete/', views.delete_group, name='delete_group'),
    path('manage/<int:course_id>/groups/<int:group_id>/add-member/', views.add_group_member, name='add_group_member'),
    path('manage/<int:course_id>/groups/<int:group_id>/remove-member/', views.remove_group_member, name='remove_group_member'),
    path('manage/<int:course_id>/', views.manage_course, name='manage_course'),
    path('manage/module/create/<int:course_id>/', views.create_module, name='create_module'),
    path('manage/module/<int:module_id>/', views.get_module, name='get_module'),
    path('manage/module/<int:module_id>/update/', views.update_module, name='update_module'),
    path('manage/module/<int:module_id>/delete/', views.delete_module, name='delete_module'),
    path('manage/update_module_order/', views.update_module_order, name='update_module_order'),
    path('manage/lesson/<int:lesson_id>/', views.get_lesson, name='get_lesson'),
    path('manage/create_lesson/<int:module_id>/', views.create_lesson, name='create_lesson'),
    path('manage/delete_lesson/<int:lesson_id>/', views.delete_lesson, name='delete_lesson'),
    path('manage/save_lesson/<int:lesson_id>/', views.save_lesson, name='save_lesson'),
    path('api/groups/<int:group_id>/members/', views.get_group_members, name='get_group_members'),
    path('module/<int:module_id>/lesson/<int:lesson_id>/create-jupyter-exercise/', 
         views.create_jupyter_exercise, 
         name='create_jupyter_exercise'),
    path('module/<int:module_id>/lesson/<int:lesson_id>/create-jupyter-exercise-ajax/', 
         views.create_jupyter_exercise_ajax, 
         name='create_jupyter_exercise_ajax'),
    path('exercise/<int:exercise_id>/edit-jupyter/', 
         views.edit_jupyter_exercise, 
         name='edit_jupyter_exercise'),
    path('check-upload-progress/', views.check_upload_progress, name='check_upload_progress'),
    path('lesson/<int:lesson_id>/', views.lesson_detail, name='lesson_detail'),
    path('lesson/<int:lesson_id>/complete/', views.complete_lesson, name='complete_lesson'),
    path('enroll/<int:course_id>/', views.course_enroll, name='course_enroll'),
    path('<int:course_id>/', views.course_overview, name='course_overview'),
    path('api/modules/<int:module_id>/lessons/reorder/', views.reorder_lessons, name='reorder_lessons'),
    path('lesson/<int:lesson_id>/delete-jupyter-file/', 
         views.delete_jupyter_file, 
         name='delete_jupyter_file'),
    path('lesson/<int:lesson_id>/delete-material/<int:material_id>/', 
         views.delete_material, 
         name='delete_material'),
    path('lesson/<int:lesson_id>/submit-exercise/', 
         views.submit_exercise, 
         name='submit_exercise'),
    path('submissions/', views.submissions_dashboard, name='submissions_dashboard'),
    path('submissions/exercise/<int:exercise_id>/', views.exercise_submissions, name='exercise_submissions'),
    path('submissions/statistics/', views.submission_statistics, name='submission_statistics'),
    path('submissions/<int:submission_id>/grade/', views.grade_submission, name='grade_submission'),
    path('<int:course_id>/groups/list/', views.list_groups, name='list_groups'),
    path('<int:course_id>/groups/join/', views.join_group, name='join_group'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/change-role/', views.admin_change_role, name='admin_change_role'),
    path('exercise/<int:exercise_id>/upload-reference/', 
         views.upload_reference_solution, 
         name='upload_reference_solution'),
]