"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import logging
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nc00o1hsog1j=az)u_unt1yvn5s#*ukuyueih9y9o%m#rmr6&r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['1985609f-7839-4819-8840-2d38548e4ea5.ma.bw-cloud-instance.org',
                 'databrix.org',
                 '127.0.0.1',
                 'localhost',
                 '193.196.55.219',
                 env.get('ALLOWED_HOSTS')
]
                  
CSRF_TRUSTED_ORIGINS = [
    'https://1985609f-7839-4819-8840-2d38548e4ea5.ma.bw-cloud-instance.org',
    'http://127.0.0.1',
    'http://localhost',
    'http://193.196.55.219',
    'https://databrix.org',
    env.get('CSRF_TRUSTED_ORIGINS')
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shibboleth',
    'course.apps.CourseConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'course.shib_middleware.CustomShibbolethMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shibboleth.context_processors.login_link',
                'shibboleth.context_processors.logout_link',
                'course.views.course_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#   'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db', 'db.sqlite3'),
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "webapp-db",
        "USER": "postgres",
        "PASSWORD": "databrix",
        "HOST": "singlekursweb-database",
    }
}

# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'shibboleth.backends.ShibbolethRemoteUserBackend',
]

# settings.py
AUTH_USER_MODEL = 'course.CustomUserModel'

SHIBBOLETH_ATTRIBUTE_MAP = {
    "HTTP_MAIL": (True, "email"),
    "HTTP_GIVENNAME": (True, "first_name"),
    "HTTP_SN": (True, "last_name"),
    "HTTP_UID": (True, "username"),
    "HTTP_UNSCOPED_AFFILIATION": (False, "affiliation"),
}

# Add this setting to specify which attributes are required
SHIBBOLETH_REQUIRED_ATTRIBUTES = ['username', 'email', 'first_name', 'last_name']


LOGIN_URL = '/Shibboleth.sso/Login'
LOGIN_REDIRECT_URL = '/course/home/'
LOGOUT_URL = '/Shibboleth.sso/Logout'
LOGOUT_REDIRECT_URL = '/'
SHIBBOLETH_FORCE_REAUTH_SESSION = False

# Update these Shibboleth settings
SHIBBOLETH_LOGIN_URL = '/Shibboleth.sso/Login' 
SHIBBOLETH_LOGOUT_URL = '/Shibboleth.sso/Logout'

# Example addition
SHIBBOLETH_EXEMPT_PATHS = [
    '/static/',
    '/admin',
    '/Shibboleth.sso',
    '/login',
    '/logout',
    '/jsi18n/',
]

# Security Settings
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Add this line
USE_X_FORWARDED_HOST = True  # Add this line
USE_X_FORWARDED_PORT = True  # Add this line
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'course.shibboleth_views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'course.shib_middleware': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'course.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.core.mail': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add this to ensure admin static files are included
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Enable serving static files in production
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media and Data Storage Configuration
DATA_URL = '/data/'
DATA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = DATA_URL + 'media/'
MEDIA_ROOT = os.path.join(DATA_ROOT, 'media')

# Specific directories for different types of files
USER_FILES_ROOT = os.path.join(DATA_ROOT, 'user_directories')
EXERCISE_FILES_ROOT = os.path.join(DATA_ROOT, 'exercise_files')
EXERCISE_SUBMISSIONS_ROOT = os.path.join(DATA_ROOT, 'exercise_submissions')

# Create necessary directories
REQUIRED_DIRS = [
    DATA_ROOT,
    USER_FILES_ROOT,
    EXERCISE_FILES_ROOT,
    MEDIA_ROOT,
    EXERCISE_SUBMISSIONS_ROOT,
    STATIC_ROOT,
]

for directory in REQUIRED_DIRS:
    os.makedirs(directory, exist_ok=True)

# Storage Configuration
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': DATA_ROOT,
            'base_url': DATA_URL,
        }
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024  # 2GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024 * 1024  # 2GB
MAX_UPLOAD_SIZE = 2 * 1024 * 1024 * 1024  # 2GB

# Temporary file settings
FILE_UPLOAD_TEMP_DIR = os.path.join(DATA_ROOT, 'tmp')
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# Security Settings
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True


# Email Settings using AWS SES
# EMAIL_BACKEND = 'django_ses.SESBackend'
# DEFAULT_FROM_EMAIL = 'info@databrix.org'
# These are optional if you are using AWS IAM Roles https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html
# AWS_ACCESS_KEY_ID = 'AKIA'
# AWS_SECRET_ACCESS_KEY = 'Ll4If'
# https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html
# AWS_SESSION_PROFILE = 'YOUR-PROFILE-NAME'
# Additionally, if you are not using the default AWS region of us-east-1,
# you need to specify a region, like so:
# AWS_SES_REGION_NAME = 'eu-west-1'
# AWS_SES_REGION_ENDPOINT = 'email.eu-west-1.amazonaws.com'

# Email Settings using Brevo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'securesmtp.t-online.de'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


EMAIL_HOST_PASSWORD = "Databrix-2025"
SUPPORT_EMAIL = ["yuqiang.gu@dhbw-stuttgart.de","udo.heuser@dhbw-stuttgart.de"]
DEFAULT_FROM_EMAIL = "dhbw-stuttgart@t-online.de"
EMAIL_HOST_USER = "dhbw-stuttgart@t-online.de"